[Main]
ShowOnlyPlayerDamage=false
; Show damage dealt only by player?
; boolean, true

ShowZeroDamage=true
; Show zero damage?
; boolean, false

FontName=Comic Sans MS
; Font used to write damage values
; string, Comic Sans MS

FontSize=25
; Font size for damage values
; number, 25
; 0|100|1

FontBold=false
; Should font be bolder
; boolean, true

DynamicFontSize=true
; Scale damage value size depending on distance to enemy
; boolean, true

DamageOverTime=true
; Show damage over time
; boolean, true
