[Main]
eCDELocatorToggleHotkey=Y
; Turns locator on/off
; key, Y

SearchDistance=3500.000000
; How far locator search for items
; number, 3500.0
; 100|10000|100

EntityIconSize=15
; Icon size rendered for each item
; number, 15
; 0|100|1

[IndicatorIcon]
IndicatorIconEnabled=true
; Should locator icon be visible
; boolean, false

IndicatorIconSize=16
; Icon size for locator indicator
; number, 16
; 0|100|1

IndicatorIconPosTopX=98.500000
; Position from left of screen in % of screen
; number, 98.500000
; 0|100|0.5

IndicatorIconPosTopY=4.500000
; Position from top of screen in % of screen
; number, 4.500000
; 0|100|0.5

[Filter]
ShowItemMeleeWeapon=true
; Search for melee weapons
; boolean, false

ShowItemRangedWeapon=true
; Search for ranged weapons
; boolean, false

ShowItemMunition=true
; Search for munition
; boolean, false

ShowItemArmor=true
; Search for armor
; boolean, false

ShowItemShield=true
; Search for shields
; boolean, false

ShowItemHelmet=true
; Search for helmets
; boolean, false

ShowItemRing=true
; Search for rings
; boolean, false

ShowItemAmulet=true
; Search for amulets
; boolean, false

ShowItemTeleport=true
; Search for teleport stones
; boolean, false

ShowItemScroll=true
; Search for scrolls
; boolean, false

ShowItemMisc=true
; Search for misc items
; boolean, false

ShowItemFood=true
; Search for food
; boolean, false

ShowItemPlant=true
; Search for plants
; boolean, false

ShowItemPlantPerm=true
; Search for special plants
; boolean, false

ShowItemDoc=true
; Search for documents
; boolean, false

ShowItemPotion=true
; Search for potions
; boolean, false

ShowItemPotionPerm=true
; Search for special potions
; boolean, false

ShowItemTrophy=true
; Search for trophies
; boolean, false

ShowItemStoneTablet=true
; Search for stone tablets
; boolean, false

ShowInteractBookstand=true
; Search for bookstands
; boolean, false

ShowInteractOre=true
; Search for ore
; boolean, false

ShowInteractStoneWheel=true
; Search for stone wheels
; boolean, false

ShowInteractTreasure=true
; Search for buried treasures
; boolean, false

ShowChestNormal=true
; Search for normal chests
; boolean, false

ShowChestOld=true
; Search for old chests
; boolean, false

ShowChestHeavy=true
; Search for heavy chests
; boolean, false

ShowChestRich=true
; Search for rich chests
; boolean, false

ShowNpcDeadNotEmpty=true
; Search for not empty bodies
; boolean, false

ShowSmallAndFarmAnimals=true
; Search for farm animals
; boolean, false

ShowHumanHostile=true
; Search for hostile NPCs
; boolean, false

ShowHumanPeaceOrAngry=true
; Search for peaceful NPCs
; boolean, false

ShowOrcHostile=true
; Search for hostile orcs
; boolean, false

ShowOrcPeaceOrAngry=true
; Search for peaceful orcs
; boolean, false

ShowUndeadHostile=true
; Search for hostile undead
; boolean, false

ShowUndeadPeace=true
; Search for peaceful undead
; boolean, false

ShowMonsterHostile=true
; Search for hostile monsters
; boolean, false

ShowMonsterPeace=true
; Search for peaceful monsters
; boolean, false

ShowQuestKillTargets=true
; Search for quest kill targets
; boolean, false

ShowQuestItems=true
; Search for quest items
; boolean, false
